//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeKafe.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasaHareketleri
    {
        public int MasaHareketID { get; set; }
        public string SatisKodu { get; set; }
        public Nullable<int> Miktari { get; set; }
        public Nullable<decimal> BirimFiyati { get; set; }
        public string MasaAciklamasi { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual Masalar Masalar { get; set; }
    }
}
