//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeKafe.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Masalar()
        {
            this.MasaHareketleri = new HashSet<MasaHareketleri>();
        }
    
        public int MasaID { get; set; }
        public string MasaAd { get; set; }
        public string MasaAciklama { get; set; }
        public Nullable<bool> Durumu { get; set; }
        public Nullable<bool> RezerveMi { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
        public Nullable<System.DateTime> SonİslemTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasaHareketleri> MasaHareketleri { get; set; }
    }
}
