//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeKafe.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KafeEntities : DbContext
    {
        public KafeEntities()
            : base("name=KafeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KullaniciHareketleri> KullaniciHareketleri { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<MasaHareketleri> MasaHareketleri { get; set; }
        public virtual DbSet<Masalar> Masalar { get; set; }
        public virtual DbSet<Menuler> Menuler { get; set; }
        public virtual DbSet<OdemeHareketleri> OdemeHareketleri { get; set; }
        public virtual DbSet<Roller> Roller { get; set; }
        public virtual DbSet<Satislar> Satislar { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
    }
}
