//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeKafe.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdemeHareketleri
    {
        public int OdemeID { get; set; }
        public string SatisKod { get; set; }
        public string OdemeTuru { get; set; }
        public Nullable<decimal> Odenen { get; set; }
        public string OdemeAciklamasi { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
