//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeKafe.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roller
    {
        public int RoID { get; set; }
        public int KullaniciId { get; set; }
        public string FromText { get; set; }
        public string ControlName { get; set; }
        public string ControlCaption { get; set; }
    }
}
