//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeKafe.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satislar
    {
        public int SatisID { get; set; }
        public string SatisKodu { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public Nullable<decimal> Odenen { get; set; }
        public Nullable<decimal> Kalan { get; set; }
        public string SatisAciklamasi { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<System.DateTime> SonİslemTarihi { get; set; }
    }
}
