//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeKafe.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int UrunID { get; set; }
        public int MenuId { get; set; }
        public string UrunKodu { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<decimal> BirimFiyati { get; set; }
        public string UrunAciklama { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Menu { get; set; }
    
        public virtual Menuler Menuler { get; set; }
    }
}
